name: ðŸš€ Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy to cPanel
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ”¨ Install Dependencies and Build Project
        run: |
          npm install
          npm run build  # Ensure this is correct

      - name: ðŸ“‚ Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: www.mmadinah.com
          username: ${{ secrets.CPANEL_USER }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          local-dir: ./dist/
          server-dir: /zoom-it-beckend.mmadinah.com/

      - name: ðŸ”‘ SSH and restart Node app
        uses: appleboy/ssh-action@master
        with:
          host: 209.182.237.105
          username: ${{ secrets.CPANEL_USER }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 2222 # <- Add your SSH port here
          script: |
            cd zoom-it-beckend.mmadinah.com
            npm install --omit=dev
            npx pm2 restart all || npx pm2 start server.js --name "zoom-it"
